apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: pangeo-deploy
version: 0.1.0
dependencies:
  - name: daskhub
    version: "2021.11.2"
    repository: https://helm.dask.org
    import-values:
      - child: rbac
        parent: rbac
  - name: enterprise-gateway
    version: "2.5.0"
    repository: 'https://charts.spot.io'
  - name: redis
    version: "15.6.4"
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: Dhamma Kimpara
    email: dhamma.kimpara@colorado.edu