redis:
  auth:
    enabled: false
daskhub:
  jupyterhub:
    # couldn't get tls to work :/
    # proxy: 
    #  service:
    #    type: LoadBalancer
    #  https:
    #    enabled: true
    #    hosts:
    #      - https://http://ip.nip.io
    #    letsencrypt:
    #      contactEmail: "dhamma.kimpara@colorado.edu"
    hub:
      extraEnv:
        JUPYTER_GATEWAY_URL: 'enterprise-gateway'
    singleuser:
      memory:
          limit: 4G
          guarantee: 2G
      defaultUrl: "/lab" 
      extraEnv:
        DASK_GATEWAY__CLUSTER__OPTIONS__IMAGE: '{JUPYTER_IMAGE_SPEC}'
        GET_HOSTS_FROM: 'dns'
        REDIS_HOST: 'app-redis-master'
  dask-gateway:
    gateway:
      extraConfig:
        optionHandler: |
          from dask_gateway_server.options import Options, Integer, Float, String
          def option_handler(options):
              if ":" not in options.image:
                  raise ValueError("When specifying an image you must also provide a tag")
              return {
                  "image": options.image,
              }
          c.Backend.cluster_options = Options(
              String("image", default="pangeo/base-notebook:2020.07.28", label="Image"),
              handler=option_handler,
          )
enterprise-gateway:
  kernel:
    whitelist: 
      - pangeo_base
    defaultKernelName: pangeo_base
  kernelspecs:
    image: dkimpara/custom-image:latest