daskhub:
  jupyterhub:
    #proxy:
    #  service:
    #    type: LoadBalancer
    #  https:
    #    enabled: true
    #    hosts:
    #      - "35.224.174.20.nip.io"
      #  letsencrypt:
     #     contactEmail: "dhamma.kimpara@colorado.edu"
    hub:
      extraEnv:
        JUPYTER_GATEWAY_URL: 'enterprise-gateway'
    singleuser:
      #image:
       # name: pangeo/base-notebook  # Image to use for singleuser environment. Must include dask-gateway.
        #tag: 2021.06.05
      defaultUrl: "/lab" 
      extraEnv:
        DASK_GATEWAY__CLUSTER__OPTIONS__IMAGE: '{JUPYTER_IMAGE_SPEC}'
  dask-gateway:
    gateway:
      extraConfig:
        optionHandler: |
          from dask_gateway_server.options import Options, Integer, Float, String
          def option_handler(options):
              if ":" not in options.image:
                  raise ValueError("When specifying an image you must also provide a tag")
              return {
                  "image": options.image,
              }
          c.Backend.cluster_options = Options(
              String("image", default="pangeo/base-notebook:2020.07.28", label="Image"),
              handler=option_handler,
          )
enterprise-gateway:
  kernel:
    whitelist: 
      - pangeo_base
    defaultKernelName: pangeo_base
  kernelspecs:
    image: dkimpara/custom-image:latest